### ISSUE TITLE
Tie Results in point awarded to the computer

### ISSUE THREAD

**Issue by AkhilBabuM** [mrmasterb4/rockpaperscissors#1]
I just stumbled across your submission through theodinproject,
If its a tie, a point is awarded to the computer due to the code
```
if (finalresult === "win") {
        user++;
}
else {
        computer++;
}
```

To fix it, try
```
if (finalresult === "win") {
        user++;
}else if (finalresult === "lose"){
        computer++;
}
```

**Comment by mrmasterb4** [comment]
You're right! I forgot to add handling for this. Thank you and fixed.
